name: Build and Deploy

on:
  push:
    tags:
      - 'v*.*.*'    # Match version tags
  workflow_dispatch:      

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        go-version: ['1.22.x']
        include:
          - os: windows-latest
            arch: amd64
            target_os: windows
            target_arch: amd64
            output: bettercap.exe

    env:
      TARGET_OS: ${{ matrix.target_os }}
      TARGET_ARCH: ${{ matrix.target_arch }}
      GO_VERSION: ${{ matrix.go-version }}
      OUTPUT: ${{ 'bettercap' }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Install libusb via mingw (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      uses: msys2/setup-msys2@v2
      with:
        install: |-
          mingw64/mingw-w64-x86_64-libusb
          mingw64/mingw-w64-x86_64-pkg-config

    - name: Install other Dependencies (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        choco install openssl.light -y
        choco install make -y
        choco install 7zip -y
        choco install zadig -y
        curl -L "https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip" -o "C:\wpcap-sdk.zip"
        7z x -y "C:\wpcap-sdk.zip" -o"C:\winpcap"
        echo "D:\a\_temp\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Build
      run: make -e TARGET="${{ env.OUTPUT }}"

  deploy:
    needs: [build]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    name: Release
    runs-on: windows-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v2
          with:
            submodules: true

        - name: Upload Release Assets
          uses: softprops/action-gh-release@v1
          with:
            files: |
                bettercap.exe
    env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
